# Generated by Django 6.0 on 2026-01-10 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='用户名（冗余存储）', max_length=150)),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('device_create', '创建设备'), ('device_update', '更新设备'), ('device_delete', '删除设备'), ('channel_create', '创建通道'), ('channel_update', '更新通道'), ('channel_delete', '删除通道'), ('run_create', '创建运行批次'), ('run_update', '更新运行批次'), ('run_delete', '删除运行批次'), ('command_send', '发送命令'), ('user_create', '创建用户'), ('user_update', '更新用户'), ('user_delete', '删除用户'), ('user_enable', '启用用户'), ('user_disable', '禁用用户')], db_index=True, help_text='操作类型', max_length=50)),
                ('resource_type', models.CharField(blank=True, help_text='资源类型（如 device/channel）', max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='资源 ID', max_length=100)),
                ('description', models.TextField(blank=True, help_text='操作描述')),
                ('changes', models.JSONField(blank=True, help_text='变更内容（JSON）', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='请求 IP', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent')),
                ('success', models.BooleanField(default=True, help_text='操作是否成功')),
                ('error_message', models.TextField(blank=True, help_text='错误信息（如果失败）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='操作用户（删除后保留日志）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'accounts_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='idx_auditlog_action_time'), models.Index(fields=['username', '-created_at'], name='idx_auditlog_user_time'), models.Index(fields=['resource_type', 'resource_id'], name='idx_auditlog_resource')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('readonly', '只读用户'), ('operator', '操作员'), ('admin', '管理员')], db_index=True, default='readonly', help_text='用户角色：readonly（只读）、operator（操作员）、admin（管理员）', max_length=20)),
                ('real_name', models.CharField(blank=True, help_text='真实姓名', max_length=100)),
                ('department', models.CharField(blank=True, help_text='部门/实验室', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='最后登录时间', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='最后登录 IP', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'accounts_userprofile',
                'indexes': [models.Index(fields=['role'], name='idx_userprofile_role'), models.Index(fields=['is_active'], name='idx_userprofile_active')],
            },
        ),
    ]
