"""
Django settings for compostlab_v2 project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

# 读取 .env（如果不存在也不报错）
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default="").split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "apps.accounts",
    "apps.devices",
    "apps.runs",
    "apps.telemetry",
    "apps.announcements",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "compostlab_v2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "compostlab_v2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {"default": env.db("DATABASE_URL")}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = env("TIME_ZONE", default="Asia/Shanghai")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploads)
# https://docs.djangoproject.com/en/6.0/howto/static-files/#serving-uploaded-files

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost:3000",
    "http://127.0.0.1:3000",
    "https://127.0.0.1:3000",
    "http://compostlab.cpolar.cn",
    "https://compostlab.cpolar.cn",
    "http://compostlab-backend-v2.cpolar.cn",
    "https://compostlab-backend-v2.cpolar.cn",
]
CORS_ALLOW_HEADERS = list(default_headers) + ["authorization"]
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# 添加以下配置
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost:3000",
    "http://127.0.0.1:3000",
    "https://127.0.0.1:3000",
    "http://compostlab.cpolar.cn",
    "https://compostlab.cpolar.cn",
    "http://compostlab-backend-v2.cpolar.cn",
    "https://compostlab-backend-v2.cpolar.cn",
]

# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),  # Access token 有效期 8 小时
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # Refresh token 有效期 7 天
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,  # 启用黑名单（通过 TokenBlacklist 实现）
    "UPDATE_LAST_LOGIN": True,  # 更新用户最后登录时间
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "JTI_CLAIM": "jti",  # JWT Token ID，用于黑名单机制
}

# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

# Python control-script model registry
# Usage: call predict("model_name", FEATURES) inside Python scripts.
CONTROL_MODEL_REGISTRY = {
    "aeration_v1": {
        "kind": "rule",
        "rule_type": "aeration",
        "thresholds": {
            "temp_feature": "temp_avg_5m",
            "temp_high": 70,
            "o2_feature": "o2_min_5m",
            "o2_low": 8,
        },
        "suggestions": {
            "on_duration_ms": 120000,
            "off_duration_ms": 0,
            "hold_duration_ms": 30000,
        },
        "confidence": {
            "on": 0.78,
            "off": 0.72,
            "hold": 0.2,
        },
    },
    "cp500_demo_control_v1": {
        "kind": "model",
        "rule_type": "aeration",
        "path": "models/cp500_demo_control_v1.pkl",
        "features": ["temp_avg_5m", "o2_min_5m", "sample_count_temp", "sample_count_o2"],
        "missing_feature_strategy": "hold",
        "default_feature_value": 0,
        "decision_map": {
            "1": "on",
            "0": "off",
        },
        "suggestions": {
            "on_duration_ms": 90000,
            "off_duration_ms": 0,
            "hold_duration_ms": 30000,
        },
    },
    "heater_v1": {
        "kind": "rule",
        "rule_type": "heater",
        "thresholds": {
            "temp_feature": "temp_avg_5m",
            "temp_low": 52,
            "temp_high": 58,
        },
        "suggestions": {
            "on_duration_ms": 90000,
            "off_duration_ms": 0,
            "hold_duration_ms": 30000,
        },
        "confidence": {
            "on": 0.76,
            "off": 0.74,
            "hold": 0.5,
        },
    },
}
