# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("maintenance", "维护通知"),
                            ("feature", "功能更新"),
                            ("announcement", "公告"),
                        ],
                        db_index=True,
                        default="announcement",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("all", "所有用户"),
                            ("admin", "管理员"),
                            ("operator", "操作员"),
                            ("readonly", "只读用户"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=20,
                        verbose_name="目标角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, db_index=True, verbose_name="是否启用"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, db_index=True, verbose_name="是否置顶"),
                ),
                (
                    "expiry_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to="auth.User",
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-is_pinned", "-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-is_pinned", "-priority", "-created_at"],
                        name="ann_ann_idx_prio_crea_5642f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now=True, db_index=True, verbose_name="阅读时间"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_records",
                        to="announcements.announcement",
                        verbose_name="公告",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_announcements",
                        to="auth.User",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告已读记录",
                "verbose_name_plural": "公告已读记录",
                "ordering": ["-read_at"],
                "unique_together": {("announcement", "user")},
            },
        ),
    ]
