# Generated by Django 6.0 on 2026-01-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('follow_run', models.BooleanField(default=True)),
                ('group', models.CharField(default='CK', max_length=32)),
                ('treatment', models.CharField(blank=True, default='', max_length=64)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('devices', models.ManyToManyField(blank=True, related_name='run_windows', to='devices.device')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='runs.run')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'start_at'], name='runs_runwin_run_id_eb5fcd_idx'), models.Index(fields=['run', 'group', 'start_at'], name='runs_runwin_run_id_3f03a8_idx')],
            },
        ),
    ]
