# Generated by Django 6.0 on 2026-01-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='runwindow',
            name='runs_runwin_device__004085_idx',
        ),
        migrations.AddField(
            model_name='runwindow',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='run_windows', to='devices.device'),
        ),
        migrations.RemoveField(
            model_name='runwindow',
            name='device',
        ),
    ]
