# Generated by Django 6.0 on 2026-01-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('api_token', models.CharField(blank=True, default='', editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('post_topic', models.CharField(blank=True, default='', max_length=256)),
                ('response_topic', models.CharField(blank=True, default='', max_length=256)),
                ('note', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['code'], name='devices_dev_code_767230_idx'), models.Index(fields=['is_active', 'last_seen_at'], name='devices_dev_is_acti_930b29_idx')],
            },
        ),
        migrations.CreateModel(
            name='ControlTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名称，如：曝气开启', max_length=128)),
                ('description', models.CharField(blank=True, default='', help_text='模板描述', max_length=256)),
                ('payload', models.JSONField(default=dict, help_text='命令payload')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_templates', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, help_text='关联设备（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_templates', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='devices_con_device__554485_idx'), models.Index(fields=['is_active'], name='devices_con_is_acti_2d918b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metric', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('role', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='devices.device')),
            ],
            options={
                'ordering': ['device_id', 'code'],
                'indexes': [models.Index(fields=['device', 'code'], name='devices_cha_device__15b0f3_idx'), models.Index(fields=['code'], name='devices_cha_code_960334_idx'), models.Index(fields=['device', 'is_active'], name='devices_cha_device__4e149f_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'code'), name='uq_channel_device_code')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('acked', 'Acked'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['device', 'status', 'created_at'], name='devices_dev_device__d88676_idx')],
            },
        ),
    ]
