# Generated by Django 6.0 on 2026-01-11 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('runs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='脚本名称，如：高温自动降温', max_length=128)),
                ('description', models.CharField(blank=True, default='', help_text='脚本描述', max_length=512)),
                ('script_type', models.CharField(choices=[('threshold', '阈值触发'), ('schedule', '定时执行'), ('hybrid', '混合模式（阈值+定时）'), ('python', 'Python脚本')], default='threshold', help_text='脚本类型', max_length=20)),
                ('threshold_config', models.JSONField(blank=True, default=dict, help_text='阈值配置，例如: {"metric": "temperature", "operator": ">=", "value": 75, "action": "pump_off"}')),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text='定时配置，例如: {"cron": "0 9 * * *", "commands": [...]}')),
                ('python_code', models.TextField(blank=True, help_text='Python脚本代码（script_type=python时使用）')),
                ('command_template', models.JSONField(default=dict, help_text='命令模板，例如: {"commands": [{"command": "pump", "action": "on"}]}')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='优先级，数字越大越优先执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_templates', to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(blank=True, help_text='应用到哪些设备', related_name='script_templates', to='devices.device')),
                ('run', models.ForeignKey(blank=True, help_text='应用到哪个批次', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_templates', to='runs.run')),
            ],
            options={
                'db_table': 'devices_scripttemplate',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], db_index=True, default='pending', max_length=16)),
                ('trigger_reason', models.CharField(blank=True, default='', help_text='触发原因，如：threshold_exceeded, schedule, manual', max_length=64)),
                ('commands', models.JSONField(default=list, help_text='实际下发的命令列表')),
                ('result', models.JSONField(blank=True, default=dict, help_text='执行结果详情')),
                ('error_message', models.TextField(blank=True, default='', help_text='错误信息（如果失败）')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='计划执行时间', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='实际开始时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='手动执行的用户（null表示自动执行）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_executions', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(help_text='目标设备', on_delete=django.db.models.deletion.CASCADE, related_name='script_executions', to='devices.device')),
                ('script', models.ForeignKey(help_text='执行的脚本模板', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='devices.scripttemplate')),
            ],
            options={
                'db_table': 'devices_scriptexecution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scripttemplate',
            index=models.Index(fields=['script_type', 'is_active'], name='devices_scr_script__dca71d_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttemplate',
            index=models.Index(fields=['run', 'is_active'], name='devices_scr_run_id_f6b133_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['script', 'status'], name='devices_scr_script__e9f206_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['device', 'created_at'], name='devices_scr_device__2efc71_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptexecution',
            index=models.Index(fields=['status', 'scheduled_at'], name='devices_scr_status_b78285_idx'),
        ),
    ]
