# Generated by Django 4.2 on 2026-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ip_address",
            field=models.CharField(blank=True, default="", help_text="设备上线时的 IP 地址", max_length=64),
        ),
        migrations.AddField(
            model_name="device",
            name="register_at",
            field=models.DateTimeField(blank=True, help_text="设备首次注册时间", null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="configuration",
            field=models.JSONField(blank=True, default=dict, help_text="设备配置信息"),
        ),
    ]
