from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from django.conf import settings
from django.http import Http404, JsonResponse
from django.views import View


FILENAME_RE = re.compile(r"^(?P<date>\d{4}-\d{2}-\d{2})_daily_digest\.html$")
TITLE_RE = re.compile(r"<title>(?P<title>.*?)</title>", re.IGNORECASE | re.DOTALL)
SUMMARY_RE = re.compile(r"border-left:\s*4px[^>]*>(?P<summary>.*?)</div>", re.IGNORECASE | re.DOTALL)
TAG_RE = re.compile(r"<[^>]+>")
SCRIPT_RE = re.compile(r"<script\b[^<]*(?:(?!</script>)<[^<]*)*</script>", re.IGNORECASE)
EVENT_HANDLER_RE = re.compile(r"\s+on[a-zA-Z]+\s*=\s*(['\"]).*?\1", re.IGNORECASE | re.DOTALL)


@dataclass(frozen=True)
class DigestFile:
    slug: str
    date: str
    path: Path


def literature_root() -> Path:
    return Path(
        getattr(settings, "LITERATURE_ARTICLE_ROOT", settings.MEDIA_ROOT / "literature" / "articles")
    ).resolve()


def list_digest_files() -> list[DigestFile]:
    by_slug: dict[str, DigestFile] = {}
    root = literature_root()
    if not root.exists():
        return []
    for path in root.glob("*_daily_digest.html"):
        match = FILENAME_RE.match(path.name)
        if not match:
            continue
        date = match.group("date")
        by_slug.setdefault(date, DigestFile(slug=date, date=date, path=path.resolve()))
    return sorted(by_slug.values(), key=lambda item: item.date, reverse=True)


def find_digest(slug: str) -> DigestFile:
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", slug):
        raise Http404("digest not found")

    root = literature_root()
    path = (root / f"{slug}_daily_digest.html").resolve()
    if root in path.parents and path.exists() and path.is_file():
        return DigestFile(slug=slug, date=slug, path=path)

    raise Http404("digest not found")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def clean_text(value: str) -> str:
    text = TAG_RE.sub("", value)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def extract_title(html: str, fallback: str) -> str:
    match = TITLE_RE.search(html)
    if not match:
        return fallback
    return clean_text(match.group("title")) or fallback


def extract_summary(html: str) -> str:
    match = SUMMARY_RE.search(html)
    if not match:
        return ""
    return clean_text(match.group("summary"))[:240]


def absolutize_media_urls(html: str, request) -> str:
    media_url = settings.MEDIA_URL.rstrip("/")
    media_prefixes = (f'src="{media_url}/', f"src='{media_url}/")
    if not any(prefix in html for prefix in media_prefixes):
        return html

    absolute_media = request.build_absolute_uri(f"{media_url}/").rstrip("/")
    html = html.replace(f'src="{media_url}/', f'src="{absolute_media}/')
    html = html.replace(f"src='{media_url}/", f"src='{absolute_media}/")
    return html


def sanitize_html(html: str, request=None) -> str:
    # The source HTML is generated by our own pipeline. Keep inline styles for WeChat/site parity,
    # but remove executable script and inline event attributes before returning it to the frontend.
    html = SCRIPT_RE.sub("", html)
    html = EVENT_HANDLER_RE.sub("", html)
    if request is not None:
        html = absolutize_media_urls(html, request)
    return html


def serialize_digest(item: DigestFile, include_html: bool = False, request=None) -> dict:
    html = read_text(item.path)
    payload = {
        "slug": item.slug,
        "date": item.date,
        "title": extract_title(html, f"{item.date} 文献分析"),
        "summary": extract_summary(html),
        "filename": item.path.name,
    }
    if include_html:
        payload["html"] = sanitize_html(html, request=request)
    return payload


class LiteratureDigestListView(View):
    def get(self, request):
        limit = max(1, min(int(request.GET.get("limit", 30)), 100))
        items = [serialize_digest(item) for item in list_digest_files()[:limit]]
        return JsonResponse({"data": items})


class LiteratureDigestDetailView(View):
    def get(self, request, slug: str):
        return JsonResponse({"data": serialize_digest(find_digest(slug), include_html=True, request=request)})
