# Generated by Django 6.0 on 2026-01-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryKV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('ts', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('quality_flag', models.CharField(default='OK', max_length=16)),
                ('source', models.CharField(default='mqtt', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'db_table': 'telemetry_telemetrykv',
                'indexes': [models.Index(fields=['device', 'code', 'ts'], name='idx_device_code_ts'), models.Index(fields=['device', 'code', 'ts', 'value'], name='idx_device_code_ts_value'), models.Index(fields=['code', 'ts'], name='idx_code_ts'), models.Index(fields=['device', 'ts'], name='idx_device_ts'), models.Index(fields=['device', 'code', '-ts'], name='idx_device_code_ts_desc'), models.Index(fields=['ts', 'device', 'code'], name='idx_ts_device_code')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=256)),
                ('ts_received', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(default='mqtt', max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_packets', to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'ts_received'], name='telemetry_t_device__c7835b_idx'), models.Index(fields=['device', 'payload_hash'], name='telemetry_t_device__04cb61_idx')],
            },
        ),
    ]
